# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ demo ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
         # Runs a set of commands using the runners shell
      - name: Get Source
        run: |
          cd /home/ubuntu
          [ -d barcode-reader-javascript-samples ] && cd barcode-reader-javascript-samples && git pull https://github.com/Dynamsoft/barcode-reader-javascript-samples.git
          [ ! -d barcode-reader-javascript-samples ] && git clone --depth 1 https://github.com/Dynamsoft/barcode-reader-javascript-samples.git && cd barcode-reader-javascript-samples 
          
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_DEMO_SERVER }}
          username: ${{ secrets.FTP_DEMO_USERNAME }}
          password: ${{ secrets.FTP_DEMO_PASSWORD }}
          port: 2122 
          local-dir: /home/ubuntu/barcode-reader-javascript-samples/
          server-dir: /demo.dynamsoft.com/Samples/DBR/JS/
